#!/bin/sh
set -eux
for path in sources/*; do
  for _ in {1..3}; do
    ! "$path" || break
  done
done
./concatenate-data
echo '<meta content="0; url=https://www.booksie.org/" http-equiv="refresh">' > dist/index.html
