#!/bin/sh
set -eu
if [ -d dist/.git ]; then
  find dist -type f -exec chmod 644 {} +
  git -C dist pull
else
  [ ! -d dist ] || rm -fr dist
  git clone -b gh-pages https://${GITHUB_TOKEN+"$GITHUB_TOKEN"@}github.com/sgtpep/booksie-data.git dist
fi
for path in sources/*; do
  for _ in {1..3}; do
    ! "$path" || break
  done
done
./concatenate-data
echo '<meta content="0; url=https://www.booksie.org/" http-equiv="refresh">' > dist/index.html
