name: CI
on:
  schedule:
    - cron: "0 0 * * 6"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt update
      - run: sudo apt install ghostscript nodejs poppler-utils
      - run: npm i
      - uses: actions/checkout@v2
        with:
          repository: sgtpep/booksie-data
          path: dist
          ref: gh-pages
      - run: ./build
      - run: git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'
      - run: ./deploy
